### ISSUE TITLE
Inconsistent Square Size on Emoji Reveal Disrupts Grid Layout

### ISSUE THREAD

**Issue by diamond-one** [YoadBarok/edens-memory-game#1]
### Bug Report

**Title:** Square Size Increases When Revealing Emoji

**Priority:** High

**Severity:** Major

**Environment:**
- **OS:** Windows 10
- **Browser:** Google Chrome Version 103.0.5060.114
- **App Version:** 1.0.2
- **Device:** Desktop

**Description:**
When a square is clicked to reveal an emoji, the square increases in size, disrupting the layout of the 6x6 grid. This affects the visual consistency and user experience, making it difficult to play the game as intended.

**Steps to Reproduce:**
1. Open the web app.
2. Click on any pink square to reveal the hidden emoji.

**Expected Result:**
The square should reveal the emoji without changing its size, maintaining the consistent 6x6 grid layout.

**Actual Result:**
The square increases in size when the emoji is revealed, causing the grid to look uneven and disrupting the overall design.

**Relevant Code Snippet:**
The issue appears to be related to the following CSS classes in `Square.css`:

```css
.square {
  display: flex;
  justify-content: center;
  align-items: center;
  cursor: pointer;
  border: 1px solid black;
  border-radius: 5px;
  aspect-ratio: 1/1;
  margin: 5px;
  transition: background-color 0.5s;
  height: 9vh; /* Ensure consistent height */
  font-size: 8vh; /* Ensure consistent font-size */
}

.big-square {
  /* height: 9vh; */ /* Comment out or remove these lines */
  /* font-size: 8vh; */
}

.small-square {
  /* height: 6vh; */
  /* font-size: 5vh; */
}

.shown {
  background-color: rgb(246, 167, 230);
  pointer-events: none;
}

.shown-eden-mode {
  background-color: rgb(246, 167, 230);
}

.hidden {
  background-color: rgb(221, 98, 204);
}

.matched {
  background-color: rgb(123, 232, 179);
  pointer-events: none;
}

.not-matched {
  background-color: rgb(255, 0, 0);
  pointer-events: none;
}
```

**Possible Cause:**
The CSS classes `.big-square` and `.small-square` include height and font-size properties that might be unintentionally applied when an emoji is revealed, causing the square size to increase.

**Suggested Fix:**
Ensure that the height and font-size properties remain consistent for the `.square` class before and after revealing the emoji. Adjust the CSS as follows:

```css
.square {
  display: flex;
  justify-content: center;
  align-items: center;
  cursor: pointer;
  border: 1px solid black;
  border-radius: 5px;
  aspect-ratio: 1/1;
  margin: 5px;
  transition: background-color 0.5s, font-size 0.5s; /* Include font-size in the transition if needed */
  height: 9vh; /* Ensure consistent height */
  font-size: 8vh; /* Ensure consistent font-size */
}

.big-square {
  /* height: 9vh; */ /* Comment out or remove these lines */
  /* font-size: 8vh; */
}

.small-square {
  /* height: 6vh; */
  /* font-size: 5vh; */
}

.shown {
  background-color: rgb(246, 167, 230);
  pointer-events: none;
}

.shown-eden-mode {
  background-color: rgb(246, 167, 230);
}

.hidden {
  background-color: rgb(221, 98, 204);
}

.matched {
  background-color: rgb(123, 232, 179);
  pointer-events: none;
}

.not-matched {
  background-color: rgb(255, 0, 0);
  pointer-events: none;
}
```

**Additional Information:**
This issue occurs consistently across different browsers and devices, suggesting a problem with the app's styling logic.

**Screenshots:**
![image](https://github.com/user-attachments/assets/a95ae9f8-bfb5-4309-8436-7e9368ba2f19)

![image](https://github.com/user-attachments/assets/b19c1575-d031-43c6-ae79-7efa6f02519a)

**Reported by:**
Long time player, first time reporter
